TRIPS_MAPPING = {
    "trip_id": {"src": "trip_id", "cast": "string"},
    "city_id": {"src": "city_id", "cast": "string", "transform": "upper"},
    "business_date": {"src": "date", "cast": "date"},
    "distance_travelled": {"src": "distance_travelled_km", "cast": "double"},
    "passenger_type": {"src": "passenger_type", "cast": "string", "transform": "lower"},
    "fare_amount": {"src": "fare_amount", "cast": "double"},
    "passenger_rating": {"src": "passenger_rating", "cast": "int"},
    "driver_rating": {"src": "driver_rating", "cast": "int"},
    "_ingest_ts": {"src": "_ingest_ts", "cast": "timestamp"},
    "_ingest_date": {"src": "_ingest_date", "cast": "date"},
    "_ingest_yyyymmdd": {"src": "_ingest_yyyymmdd", "cast": "int"},
    "_source_file": {"src": "_source_file", "cast": "string"},
    "_source_file_mod_ts": {"src": "_source_file_mod_ts", "cast": "timestamp"},
    "_source_file_size": {"src": "_source_file_size", "cast": "long"},
    "_ingest_run_id": {"src": "_ingest_run_id", "cast": "string"},
    "_record_hash": {"src": "_record_hash", "cast": "string"},
    "_replay_id": {"src": "_replay_id", "cast": "string"},
    "_backfill_id": {"src": "_backfill_id", "cast": "string"},
    "_backfill_reason": {"src": "_backfill_reason", "cast": "string"},
}

CITY_MAPPING = {
    "city_id": {"src": "city_id", "cast": "string", "transform": "upper"},
    "city_name": {"src": "city_name", "cast": "string", "transform": "initcap"},
    "_ingest_ts": {"src": "_ingest_ts", "cast": "timestamp"},
    "_ingest_date": {"src": "_ingest_date", "cast": "date"},
    "_ingest_yyyymmdd": {"src": "_ingest_yyyymmdd", "cast": "int"},
    "_source_file": {"src": "_source_file", "cast": "string"},
    "_source_file_mod_ts": {"src": "_source_file_mod_ts", "cast": "timestamp"},
    "_source_file_size": {"src": "_source_file_size", "cast": "long"},
    "_ingest_run_id": {"src": "_ingest_run_id", "cast": "string"},
    "_record_hash": {"src": "_record_hash", "cast": "string"},
}
