LATE_WINDOW_DAYS = 7
WATERMARK_DAYS = 3

FRESHNESS_SLA_HOURS = 24

GUARDRAILS_ENFORCED = True

MAX_QUARANTINE_RATE = 0.05
MAX_JOIN_DROP_RATE_CURRENT = 0.02
MAX_JOIN_DROP_RATE_ASOF = 0.02
MAX_TYPE_DRIFT_RATE = 0.001
MAX_CORRUPT_RATE = 0.001
MAX_RESCUED_RATE = 0.02

QUARANTINE_RETENTION_DAYS = 30

ENABLE_LATE_REPLAY = False
REPLAY_ID = None

BACKFILL_MODE = False
BACKFILL_START_DATE = "1900-01-01"
BACKFILL_END_DATE = "2999-12-31"
BACKFILL_ID = None
BACKFILL_REASON = None

INGEST_RUN_ID = "manual_run"